language: julia
os:
  - linux
  - osx
julia:
  - 0.7
notifications:
  email: false
git:
  depth: 99999999
matrix:
  allow_failures:
  - julia: nightly

after_success:
  - julia -e 'cd(Pkg.dir("DiscreteChoice")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("DiscreteChoice")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
